gulp/test.js
karma/karma.conf.js
settings/settings.js

* disables instanbul instrumentation
* closes #13

Debug spec files

---

dev/lint.js
settings/index.js

Lemme know what you think. Works e.g. "npm run lint project/app/common/*.js **/models/*.js".

#47: Support globs in cli for linting in v2

---

packages/availity-workflow-angular/webpack.config.production.js
packages/availity-workflow/scripts/version.js

* Fixing version bug that removes package.json contents
* Updating angular production workflow for missing loaders

Minor bug fixes

---

packages/availity-workflow-settings/index.js

Allows a function to be exported from the developer workflow.js which is used to merge the configuration

feat(settings): allow merge function

---

packages/availity-angular-kit/package.json
packages/availity-react-kit/package.json
packages/availity-workflow/README.md
packages/availity-workflow/index.js
packages/availity-workflow/scripts/build.js
packages/availity-workflow/scripts/release.js

Also cleans up some discrepancies between angular and react kit package.json to better match.
Closes #88

feat(build): expose build via av build

---

packages/availity-workflow/scripts/proxy.js

fix(proxy): don't clobber user callbacks

---

packages/availity-workflow/scripts/start.js

The options are pulled from config.development.webpackOptions and passed
to to the webpack dev server.

Honour developer-set webpack dev server options

---

packages/availity-workflow-settings/index.js

This fixes the double 'stringification' that I accidentally introduced in #103.

Stringify globals strings iff not stringified

---

.travis.yml
packages/availity-mock-server/index.js
packages/availity-mock-server/middleware/tests/headers.spec.js
packages/availity-mock-server/middleware/tests/mulit-part.spec.js
packages/availity-mock-server/response/tests/asynchronous.spec.js
packages/availity-mock-server/response/tests/behavior.spec.js
packages/availity-mock-server/response/tests/scoring.spec.js
packages/availity-mock-server/routes/tests/routes.spec.js
packages/availity-mock-server/tests/helpers.js
packages/availity-mock-server/tests/server.spec.js

https://github.com/Availity/availity-workflow/issues/135

revert async to Promise for node 6

---

README.md

Made a couple typo fixes

---

package.json
packages/workflow/README.md
packages/workflow/index.js
packages/workflow/scripts/version.js

feat(workflow): accept version when running release

---

packages/example-react/project/app/App.js

fix(example-react): make enforceActions 'observed'

---

packages/example-react/project/app/index.js

fix(example-react): include react-block-ui css

---

packages/workflow-settings/webpack/loader-eslint.js

fix(workflow-settings): emit warnings for eslint errors in webpack

---

packages/example-react/project/app/index.scss

Page suggestion returns 404: availity.github.io/availity-uikit/v3/pages/components
Options to change route:
1) http://availity.github.io/availity-uikit/v3/components
2) http://availity.github.io/availity-uikit

Update index.scss to correct route.

---

packages/workflow-plugin-react/package.json

"peerDepedencies" s/b "peerDependencies"

chore(workflow-plugin-react): fix typo

---

packages/workflow/scripts/start.js

Modified watch options to allow for any updates to our es6 scoped packages to hot reload the app. This makes debugging a lot easier when you want to make changes and check for the updated result rather than restarting the app.

refactor(workflow): allow updates inside of availity node modules

---

packages/workflow-plugin-react/test.js

fix(workflow-plugin-react): removed @testing-library/react/cleanup-after-each

---

.gitignore
packages/workflow/package.json
packages/workflow/webpack.config.js
packages/workflow/webpack.config.production.js
packages/workflow/webpack.config.profile.js
yarn.lock

See: https://www.npmjs.com/package/navigator.sendbeacon
Needed for: https://github.com/Availity/sdk-js/pull/177

feat(workflow): add navigator.sendbeacon polyfill

---

packages/mock-data/data/me.json

I've updated the mock `me.json` to reflect all the fields that return in the latest user API (me) response. 
I was a little hesitant to hardcode a current region, but I imagine anyone could use the actual regions API (getCurrentRegion) to simulate whichever region they need in their code.

Updating users/me mock response with up-to-date fields

---

docs/gatsby-config.js
docs/source/tutorial/dependency-management.md

Add dependency management doc to tutorial

docs: add dependency-management file

---

packages/workflow/package.json
packages/workflow/scripts/start.js

refactor(workflow): allow mock server to be optional

---

packages/workflow/package.json

refactor(workflow): add postcss to main dependencies

---

docusaurus/docs/index.md

1. Fork [the repository](https://github.com/availity/availity-react) and create your branch from `master`.
8. Make sure your code passed the conventional commits check. Read more about [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#summary)

docs: ie11 support

---

packages/workflow/README.md

docs(workflow): update readme

---

packages/mock-server/package.json
packages/mock-server/response/post.js
yarn.lock

refactor(mock-server): upgrade connect-busboy

---

packages/workflow/helpers/resolve-module.js
packages/workflow/loaders/loader-css.js
packages/workflow/loaders/loader-scss.js
packages/workflow/rspack.config.dev.js
packages/workflow/scripts/about.js
packages/workflow/scripts/start.js
packages/workflow/settings/index.js

fix(workflow): some more rspack config cleanup and improvements

---

packages/workflow/webpack.config.production.js

chore: add limit to file names

---

packages/workflow/webpack.config.production.js

fix(workflow): fix prod webpack config

---

packages/workflow/webpack.config.js

fix(workflow): typo fix

---

docusaurus/docs/upgrading-workflow.md
docusaurus/sidebars.js

docs: add upgrading-workflow docs

---

packages/workflow/settings/index.js
packages/workflow/settings/schema.js

I updated the schema to keep people from setting the dev server port or ekko port to 0 which was throwing an error.
I also added some `try/catch`'s and logging to hopefully expose any other errors that people may run into

fix(workflow): surface errors in logger

---

yarn.lock

chore: ensure axios is up to date

---

packages/workflow/loaders/rule-images.js
packages/workflow/package.json
yarn.lock

See https://webpack.js.org/guides/asset-modules/

fix(workflow): fix image loading for webpack 5 asset modules

---

packages/mock-server/package.json
yarn.lock

build: ensure express is up to date

---

packages/mock-server/package.json
yarn.lock

chore(mock-server): upgrade superagent

---

yarn.lock

chore: ensure ws is up to date

---

packages/workflow/jest/babel.js

See: https://babeljs.io/docs/babel-plugin-proposal-decorators

fix(workflow): enable class elements transform for @babel/preset-env to allow legacy decorators

---

yarn.lock

build: upgrade deps associated with vulnerabilities

---

example/package.json
packages/workflow-upgrade/index.js
yarn.lock

Add's the feature to rewrite the jsconfig to tsconfig in the upgrade script

feat: add rewriting jsconfig to tsconfig

---

example/package.json
packages/workflow/jest.config.js
yarn.lock

Adds defaults for test coverage that we are asking teams to add in AWS deploys

feat: add jest coverage defaults
