Availity/availity-workflow

gulp/release.js
Currently, old files in the dist/ folder are not included in the git commit when releasing a new version of an app. In other words, the old files are removed from the file system, but not removed in git. Currently, after running a release, git will show files as missing from the dist/ folder, and the developer is forced to remove them manually. These changes will correct the issue.
=> Fix release task so that deleted distributables are included in the git commit

package.json, webpack/webpack-config.js
node.js has the ability to require a json file natively without any plugin.
For our project, currently we have all the convenience of node.js-styled require/module.export through webpack, but lack native json support.
It would be nice to add such a support through https://github.com/webpack/json-loader, so that .json file can be used/required directly without module.exports as a .js file.
=> [Close #15] Feature/json support

cli/commands/init.js
Fix for #33 
Ensure toString() is called on object before performing string operations.
=> Fix keyword parsing

webpack/index.js
Remove the AllChunks flag. This was causing an issue with memory allocation during the hashing process.
=> Remove allchunks flag from the extractTextPlugin

package.json
Expose-loader 0.7.3 seems to fix the issue, so removing the pinned version
=> Remove pinned version

packages/availity-workflow-logger/README.md, packages/availity-workflow-settings/index.js, packages/availity-workflow/README.md, packages/availity-workflow/index.js, packages/availity-workflow/scripts/lint.js
Webpack Globals can better be taken advantage of when strings are represented by, wait for it, _strings_. One sample use case is storing environment-specific configuration for API routes to be determined at build time.
=> Stringify config globals to allow nested objects

packages/availity-react-kit/project/app/Request/api/requestApi.js
Bugfix. API requests in example were relative rather than absolute to origin
=> Add leading forward slash to opts

packages/availity-react-kit/package.json
reactstrap needs a peerDep of react-transition-group@^1.1.2 (this has been removed in reactstrap v5 but we cannot upgrade to that just yet)
=> fix(react kit): fix incorrect dep version

packages/availity-workflow-settings/webpack/rule-fonts.js
Imported fonts no longer need the hyphen, they just need to end with `font` before the dot-extension.
This allows for webfont to be caught.
Closes #137
=> fix(fontRule): filename no longer needs hyphen

README.md, packages/availity-workflow-angular/karma.conf.js, packages/availity-workflow-angular/karma.conf.sauce.js, packages/availity-workflow/scripts/build.js, packages/availity-workflow/scripts/start.js
Adds modifyWebpackConfig option to workflow.js. When it is a function it will be called with the current webpack config and a reference to the workflow settings
modifyWebpackConfig can be used to modify or replace the webpack config by returning the desiered final webpack config
Fixes #134, Fixes #146
This also allows many of the other "investigate webpack loader/plugin" tickets to be implemented by the user, but those tickets should remain open as they can be used to determine if those loaders/plugins should be included out of the box by default
=> feat(availity-workflow): add option to allow user to modify the webpack config

packages/availity-workflow-angular/webpack.config.js, packages/availity-workflow-angular/webpack.config.production.js, packages/availity-workflow-angular/webpack.config.profile.js, packages/availity-workflow-angular/webpack.config.test.js, packages/availity-workflow-react/webpack.config.js, packages/availity-workflow-react/webpack.config.production.js, packages/availity-workflow-react/webpack.config.profile.js
This back ports a change done to v3 to fix the same issue on v2.
=> fix(availity-workflow): include 'node_modules' when searching for modules

packages/workflow/package.json
based on https://github.com/zkat/npx/blob/6e89dbd5989366e52d3810692b1ab5889a05fbad/parse-args.js#L137-L138 npx will strip the package scope from the package name when looking for the command
=> fix(workflow): rename bin cmd to work with npx

package.json, packages/workflow-plugin-angular/scripts/init.js, packages/workflow-plugin-react/scripts/init.js, packages/workflow/README.md, packages/workflow/scripts/init.js
Added ability to create the workflow project in the current directory by using the `--current-dir` or `-c` option in the cli.
Also fixed a minor bug where the project version wasn't being set to `0.1.0` when `fs.copySync` occurred.
=> feat/same-package | Create App In Current Directory

README.md
Contribute was not in the table of contents, trying to help a contributor see the contribute section in case they did not scroll to the bottom of the readme.
For this project it is important that a contributor reads through the entire readme.
However, when groking the Readme there are two very challenging sections to the first timer. Configuration and FAQ.
A contributor needs to temporarily skip these parts to get to the all important Contribute section that tells them how to run locally without scaffolding a new react or angular app.
Putting contribute in the table of contents allows another path to that documentation.
Contribute
```
Run npm install
Run npm run bootstrap at project root
Use npm run angular to start the Angular sample application
Use npm run react to use the React sample …
```
=> docs: add contribute to the table of contents

packages/mock-data/data/legacy-permissions.json
The response for the `userPermissionsApi` was returning an array of permissions nested in the key `permissions`. The actual value should be `axiUserPermissions`.
=> fix(mock-data): mock-data response for legacy-permissions fix

packages/workflow-plugin-react/package.json, packages/workflow-settings/webpack/loader-css.js
v3 of the `css-loader` threw unwanted errors. Until this can be resolved fully through other dep upgrades/configs getting this bug fix in.
```
✖  ERROR  Failed compiling
(node:5383) UnhandledPromiseRejectionWarning: CssSyntaxError: /Users/<user>/Workspaces/<project-name>/<repo-name>/css/vendor-cd4a327eed7fc2d6d76c.css:164:32: Missed semicolon
at Input.error (/Users/<user>/Workspaces/<project-name>/<repo-name>/node_modules/postcss/lib/input.js:130:16)
at Parser.checkMissedSemicolon (
```
=> fix(workflow-settings): revert css loader to v2

packages/workflow/scripts/proxy.js
AFAICT the current condition can never be true?
With this change, it will be true when `proxyObject.statusCode` is not 304
=> fix proxy body write condition

example/project/app/App.tsx, example/project/app/chain.js, example/project/app/components/Form.tsx, packages/workflow/babel-preset.js, packages/workflow/package.json, yarn.lock
Will allow anyone on newer versions of `availity-workflow` to use optional chaining in their apps. Turning something like: 
```
return (
(resp &&
resp.data &&
resp.data.regions &&
resp.data.regions[0] &&
resp.data.regions[0].id) ||
undefined
);
```
into: 
`return resp?.data?.regions?.[0]?.id`
=> feat: add babel plugin for optional chaining

packages/workflow/package.json, yarn.lock
Reverts `sass-loader` due to intermittent issues between projects
=> fix(workflow): revert sass-loader to v7

packages/workflow/settings/schema.js
The new Joi schema for the `development.hotLoader `setting only accounted for the object notation use case and not the old way which was by a `boolean` type.
=> refactor(workflow): fixed hotloader setting not allowing boolean

packages/mock-server/response/index.js
the mock-data server doesn't handle HEAD requests even through they should get essentially be treated the same as GET
=> add support for HEAD requests in mock-server

packages/workflow/jest.config.js
- This PR fixes the regex for the test matcher in the jest config so windows can properly detect and run unit tests with jest when using this package.
=> fix testMatch regex to work correctly on windows

packages/workflow/settings/index.js, packages/workflow/webpack.config.js, packages/workflow/webpack.config.production.js, packages/workflow/webpack.config.profile.js, yarn.lock
Main portion of this PR deals with having `babel-loader` transpile dependencies inside node_modules. As time goes on, more packages are moving to modern syntax not supported in IE 11. As we upgrade Availity packages we are running into more problems in IE 11. Having babel process dependencies should help.
This PR also has some cacheGroup changes and a regex fix.
I also plan to add some of the more common polyfills we are missing in a separate PR. As an example, `@availity/hooks` depends on `react-query` which now needs `Array.prototype.includes()` to be polyfilled, that should no longer be on the developer to add. I plan to add a few more common ones plus some bundle size comparisons in that PR too.
References #212 and #98
=> Transform dependencies in node_modules

packages/workflow/package.json, packages/workflow/webpack.config.js, packages/workflow/webpack.config.production.js, yarn.lock
Fixes `@availity/hooks` issues in IE 11 due to react-query needing this polyfill for its `isDocumentVisible()` function
=> feat(workflow): add polyfill for Array.prototype.includes()

README.md, packages/workflow/babel-preset.js, packages/workflow/jest.config.js, packages/workflow/settings/index.js, packages/workflow/settings/schema.js, packages/workflow/webpack.config.js, packages/workflow/webpack.config.production.js, yarn.lock
Uses browserslist defaults and IE 11, this way we do not rely on user's having a config
=> feat(workflow): add default target to webpack config in production

README.md
Markdown did not like having the credit link in the Header. It applied the href tag correctly as #upgrading-credit, but the link didn't work. So I just moved the credit down a line
=> docs: fix broken Upgrading link in README

packages/workflow-upgrade/index.js
`npx @availity-workflow-upgrade` respects semver in `package.json` even though it deletes the project's lockfile. This is fine for all dependencies, except for `@availity/workflow`. If user is running the upgrade command, they should be upgraded to latest and greatest, not latest within semver.
Also fixes case where `eslint-config-availity` was not being installed if missing from the project. I believe we were running a synchronous command when we should have been awaiting its result
=> fix(workflow-upgrade): fixes eslint-config-availity not being installed

packages/workflow/package.json, yarn.lock
We recently received a security violation in a repository that utilizes @availity/workflow version 9.2.0 due to pulling in a vulnerable version of node-forge.
```
`-- @availity/workflow@9.2.0
`-- webpack-dev-server@4.7.3
`-- selfsigned@2.0.0
`-- node-forge@1.2.1
```
The node-forge library prior to version 1.3.0 is open to multiple vulnerabilities including Improper Verification of Cryptographic Signature (High.) 
This is pulled in via webpack-dev-server
Just bumping this to take at least the version of webpack-dev-server that upgraded the self-signed package that pulled in the vulnerable nForge dependency. 
https://github.com/webpack/webpack-dev-server/compare/v4.7.4...v4.8.0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R61
which pulls in 2.0.1 of selfsigned …
=> Fix vulnerable version of node-forge pulled in by webpack-dev-server 4 7.3

packages/workflow/babel-preset.js
This fixes an issue with `babel` assuming files under `@availity` scope will be esm. I believe this was originally set since our libs did not ship transpiled code. Setting `sourceType` to `unambiguous` will fix the issue
Credit: https://github.com/babel/babel/issues/12731
=> fix: set sourceType to unambiguous

.github/workflows/dependabot-build.yml, .github/workflows/deploy.yml
these should be the last of the deprecated actions/commands
=> chore: update gh actions

.github/workflows/dependabot-build.yml
Current dependabot workflows have builds trigger off another workflow instead of the pull_request trigger. The pattern was recommended back when they first pulled access to secrets from dependabot. However, this seems to prevent the statuses of the builds from being linked to the PR. 
They have since added separate secrets explicitly for dependabot. We should now be able to trigger directly from pull_request and if any secrets are needed add them to dependabot as needed.
=> Dependabot workflows

.github/workflows/deploy.yml, .github/workflows/pr-build.yml, package.json, yarn.lock
There was an issue with the new version of `@jscutlery/semver` so I reverted the version and added the `version` and `version:dry-run` scripts
=> build: fix versioning

packages/workflow/webpack.config.production.js
file-loader doesn't work in Node 17+ and deprecated in Webpack 5+
=> fix(workflow): replace file-loader with asset/resource

example/package.json, yarn.lock
=> build(example): upgrade axios

packages/workflow/jest.config.js
we were updating some of our dependencies to use the new tanstack react-query and found some bumps with newer ESM packages that no longer need to be transformed by jest, so we thought adding them to the default jest config might be nice too ;)
=> chore(workflow): add esm packages to jest transform ignore

packages/workflow-upgrade/index.js, packages/workflow-upgrade/package.json, packages/workflow-upgrade/project.json, yarn.lock
This pr started with trying to fix a bug where an error was thrown because the call to get peerDeps was failing because the lockfile was already deleted. I fixed this issue and also added some enhancements
- Added logs
- Increased the max buffer size for the exec call to install node_modules (I was running into a buffer overflow issue)
- Changed the way the latest version of `@availity/workflow` and `eslint-config-availity` is calculated. We now use npm to get latest version
=> fix(workflow-upgrade): fix error getting peerDeps and buffer overflow

.gitignore, packages/workflow/helpers/paths.js, packages/workflow/scripts/build.js, packages/workflow/webpack.config.js
Adds a check for `tsconfig.json` before adding the tsconfig paths plugin. Also added a try/catch to not swallow errors in the future
=> fix(workflow): check for tsconfig.json before adding plugin

packages/workflow/scripts/init.js
Fixes an issue where args would be added to the `yarn install` command when they are not supported
=> fix(workflow): add check for installer when adding args
